### ISSUE TITLE
[BUG?] Animation not working on multiactionbar

### ISSUE THREAD

**Issue by XyzKangUI** [SaneSL/sKeyPress#1]
When pressing (not clicking) a keybind that is on the default multiactionbar (not bartender/dominos) it will not animate. For now I fixed it by hooking MultiActionButtonDown. 

Edit: 
Now I am trying it with Dominos and I see it lights up on hidden bars (in my case where my chatframe is). Don't mind the blue texture. 

![image](https://user-images.githubusercontent.com/94811434/191871051-38a6866d-79f5-4467-8745-e1fd332117be.png)

**Comment by SaneSL** [comment]
Hello,

I will check this out today and push new version to CurseForge. Thanks for reporting.

**Comment by SaneSL** [comment]
Alright can you check if the new version fixed these issues

**Comment by XyzKangUI** [comment]
Great job, both issues are fixed.

**Comment by XyzKangUI** [comment]
I did find a new issue.

When you change keybindings, the binds are not working until /reload. The old configured keybind is still effective, while it has been "unbound" or changed to a differen slot. I believe this 'limitation' is caused by using SetOverrideBinding.

**Comment by SaneSL** [comment]
Hey,

I haven't had the time to check if Dominos / Bartender use different event for when keybindings are changed so I went with the easy route and just used PLAYER_ENTERING_WORLD.

I will close this request and add this as known issue to curseforge and here.

Thanks for reporting this as well.
